version: '3.8'

services:
  redis:
    image: redis/redis-stack-server:latest
    container_name: lobby-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  lobbyapi:
    build:
      context: .
      dockerfile: Lobby.Api/Dockerfile
    container_name: lobby-api-app
    ports:
      - "7001:8080"
    environment:
      - ConnectionStrings__RedisConnection=redis:6379
      - ASPNETCORE_URLS=http://+:8080
    depends_on:
      - redis

volumes:
  redis_data:
